# Generated by Django 4.1.2 on 2022-10-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_catagory', models.CharField(max_length=100)),
                ('catagory_image', models.ImageField(upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.TextField(blank=True)),
                ('p_brand', models.CharField(max_length=100)),
                ('p_price', models.PositiveIntegerField()),
                ('p_image', models.ImageField(upload_to='product_image/')),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneapp.productcategory')),
            ],
        ),
    ]
